//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ZaikoKanriHyou {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ZaikoKanriHyou_DS")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ZaikoKanriHyou_DS : global::System.Data.DataSet {
        
        private DT_D_PurchaseDataTable tableDT_D_Purchase;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public ZaikoKanriHyou_DS() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected ZaikoKanriHyou_DS(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["DT_D_Purchase"] != null)) {
                    base.Tables.Add(new DT_D_PurchaseDataTable(ds.Tables["DT_D_Purchase"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DT_D_PurchaseDataTable DT_D_Purchase {
            get {
                return this.tableDT_D_Purchase;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            ZaikoKanriHyou_DS cln = ((ZaikoKanriHyou_DS)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["DT_D_Purchase"] != null)) {
                    base.Tables.Add(new DT_D_PurchaseDataTable(ds.Tables["DT_D_Purchase"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableDT_D_Purchase = ((DT_D_PurchaseDataTable)(base.Tables["DT_D_Purchase"]));
            if ((initTable == true)) {
                if ((this.tableDT_D_Purchase != null)) {
                    this.tableDT_D_Purchase.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "ZaikoKanriHyou_DS";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ZaikoKanriHyou_DS.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableDT_D_Purchase = new DT_D_PurchaseDataTable();
            base.Tables.Add(this.tableDT_D_Purchase);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializeDT_D_Purchase() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ZaikoKanriHyou_DS ds = new ZaikoKanriHyou_DS();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void DT_D_PurchaseRowChangeEventHandler(object sender, DT_D_PurchaseRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class DT_D_PurchaseDataTable : global::System.Data.TypedTableBase<DT_D_PurchaseRow> {
            
            private global::System.Data.DataColumn columnYYYYMM;
            
            private global::System.Data.DataColumn columnSoukoCD;
            
            private global::System.Data.DataColumn columnSoukoName;
            
            private global::System.Data.DataColumn columnSKUCD;
            
            private global::System.Data.DataColumn columnJanCD;
            
            private global::System.Data.DataColumn columnSKUName;
            
            private global::System.Data.DataColumn columnLastMonthQuantity;
            
            private global::System.Data.DataColumn columnLastMonthAmount;
            
            private global::System.Data.DataColumn columnThisMonthArrivalQ;
            
            private global::System.Data.DataColumn columnThisMonthPurchaseQ;
            
            private global::System.Data.DataColumn columnThisMonthPurchaseA;
            
            private global::System.Data.DataColumn columnThisMonthSalesQ;
            
            private global::System.Data.DataColumn columnThisMonthSalesA;
            
            private global::System.Data.DataColumn columnThisMonthMoveInQ;
            
            private global::System.Data.DataColumn columnThisMonthMoveOutQ;
            
            private global::System.Data.DataColumn columnThisMonthAnyQ;
            
            private global::System.Data.DataColumn columnThisMonthAnyA;
            
            private global::System.Data.DataColumn columnTotalPurchaseGaku;
            
            private global::System.Data.DataColumn columnThisMonthQuantity;
            
            private global::System.Data.DataColumn columnLastMonthCost;
            
            private global::System.Data.DataColumn columnThisMonthCost;
            
            private global::System.Data.DataColumn columnAveragePurchaseGaku;
            
            private global::System.Data.DataColumn columnExpense;
            
            private global::System.Data.DataColumn columnColorSize;
            
            private global::System.Data.DataColumn columnThisMonthShippingQ;
            
            private global::System.Data.DataColumn columnThisMonthAmount;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DT_D_PurchaseDataTable() {
                this.TableName = "DT_D_Purchase";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal DT_D_PurchaseDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected DT_D_PurchaseDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn YYYYMMColumn {
                get {
                    return this.columnYYYYMM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SoukoCDColumn {
                get {
                    return this.columnSoukoCD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SoukoNameColumn {
                get {
                    return this.columnSoukoName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SKUCDColumn {
                get {
                    return this.columnSKUCD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn JanCDColumn {
                get {
                    return this.columnJanCD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SKUNameColumn {
                get {
                    return this.columnSKUName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn LastMonthQuantityColumn {
                get {
                    return this.columnLastMonthQuantity;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn LastMonthAmountColumn {
                get {
                    return this.columnLastMonthAmount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthArrivalQColumn {
                get {
                    return this.columnThisMonthArrivalQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthPurchaseQColumn {
                get {
                    return this.columnThisMonthPurchaseQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthPurchaseAColumn {
                get {
                    return this.columnThisMonthPurchaseA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthSalesQColumn {
                get {
                    return this.columnThisMonthSalesQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthSalesAColumn {
                get {
                    return this.columnThisMonthSalesA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthMoveInQColumn {
                get {
                    return this.columnThisMonthMoveInQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthMoveOutQColumn {
                get {
                    return this.columnThisMonthMoveOutQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthAnyQColumn {
                get {
                    return this.columnThisMonthAnyQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthAnyAColumn {
                get {
                    return this.columnThisMonthAnyA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn TotalPurchaseGakuColumn {
                get {
                    return this.columnTotalPurchaseGaku;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthQuantityColumn {
                get {
                    return this.columnThisMonthQuantity;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn LastMonthCostColumn {
                get {
                    return this.columnLastMonthCost;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthCostColumn {
                get {
                    return this.columnThisMonthCost;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AveragePurchaseGakuColumn {
                get {
                    return this.columnAveragePurchaseGaku;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ExpenseColumn {
                get {
                    return this.columnExpense;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ColorSizeColumn {
                get {
                    return this.columnColorSize;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthShippingQColumn {
                get {
                    return this.columnThisMonthShippingQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ThisMonthAmountColumn {
                get {
                    return this.columnThisMonthAmount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DT_D_PurchaseRow this[int index] {
                get {
                    return ((DT_D_PurchaseRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DT_D_PurchaseRowChangeEventHandler DT_D_PurchaseRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DT_D_PurchaseRowChangeEventHandler DT_D_PurchaseRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DT_D_PurchaseRowChangeEventHandler DT_D_PurchaseRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DT_D_PurchaseRowChangeEventHandler DT_D_PurchaseRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddDT_D_PurchaseRow(DT_D_PurchaseRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DT_D_PurchaseRow AddDT_D_PurchaseRow(
                        string YYYYMM, 
                        string SoukoCD, 
                        string SoukoName, 
                        string SKUCD, 
                        string JanCD, 
                        string SKUName, 
                        string LastMonthQuantity, 
                        string LastMonthAmount, 
                        string ThisMonthArrivalQ, 
                        string ThisMonthPurchaseQ, 
                        string ThisMonthPurchaseA, 
                        string ThisMonthSalesQ, 
                        string ThisMonthSalesA, 
                        string ThisMonthMoveInQ, 
                        string ThisMonthMoveOutQ, 
                        string ThisMonthAnyQ, 
                        string ThisMonthAnyA, 
                        string TotalPurchaseGaku, 
                        string ThisMonthQuantity, 
                        string LastMonthCost, 
                        string ThisMonthCost, 
                        string AveragePurchaseGaku, 
                        string Expense, 
                        string ColorSize, 
                        string ThisMonthShippingQ, 
                        string ThisMonthAmount) {
                DT_D_PurchaseRow rowDT_D_PurchaseRow = ((DT_D_PurchaseRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        YYYYMM,
                        SoukoCD,
                        SoukoName,
                        SKUCD,
                        JanCD,
                        SKUName,
                        LastMonthQuantity,
                        LastMonthAmount,
                        ThisMonthArrivalQ,
                        ThisMonthPurchaseQ,
                        ThisMonthPurchaseA,
                        ThisMonthSalesQ,
                        ThisMonthSalesA,
                        ThisMonthMoveInQ,
                        ThisMonthMoveOutQ,
                        ThisMonthAnyQ,
                        ThisMonthAnyA,
                        TotalPurchaseGaku,
                        ThisMonthQuantity,
                        LastMonthCost,
                        ThisMonthCost,
                        AveragePurchaseGaku,
                        Expense,
                        ColorSize,
                        ThisMonthShippingQ,
                        ThisMonthAmount};
                rowDT_D_PurchaseRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowDT_D_PurchaseRow);
                return rowDT_D_PurchaseRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                DT_D_PurchaseDataTable cln = ((DT_D_PurchaseDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new DT_D_PurchaseDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnYYYYMM = base.Columns["YYYYMM"];
                this.columnSoukoCD = base.Columns["SoukoCD"];
                this.columnSoukoName = base.Columns["SoukoName"];
                this.columnSKUCD = base.Columns["SKUCD"];
                this.columnJanCD = base.Columns["JanCD"];
                this.columnSKUName = base.Columns["SKUName"];
                this.columnLastMonthQuantity = base.Columns["LastMonthQuantity"];
                this.columnLastMonthAmount = base.Columns["LastMonthAmount"];
                this.columnThisMonthArrivalQ = base.Columns["ThisMonthArrivalQ"];
                this.columnThisMonthPurchaseQ = base.Columns["ThisMonthPurchaseQ"];
                this.columnThisMonthPurchaseA = base.Columns["ThisMonthPurchaseA"];
                this.columnThisMonthSalesQ = base.Columns["ThisMonthSalesQ"];
                this.columnThisMonthSalesA = base.Columns["ThisMonthSalesA"];
                this.columnThisMonthMoveInQ = base.Columns["ThisMonthMoveInQ"];
                this.columnThisMonthMoveOutQ = base.Columns["ThisMonthMoveOutQ"];
                this.columnThisMonthAnyQ = base.Columns["ThisMonthAnyQ"];
                this.columnThisMonthAnyA = base.Columns["ThisMonthAnyA"];
                this.columnTotalPurchaseGaku = base.Columns["TotalPurchaseGaku"];
                this.columnThisMonthQuantity = base.Columns["ThisMonthQuantity"];
                this.columnLastMonthCost = base.Columns["LastMonthCost"];
                this.columnThisMonthCost = base.Columns["ThisMonthCost"];
                this.columnAveragePurchaseGaku = base.Columns["AveragePurchaseGaku"];
                this.columnExpense = base.Columns["Expense"];
                this.columnColorSize = base.Columns["ColorSize"];
                this.columnThisMonthShippingQ = base.Columns["ThisMonthShippingQ"];
                this.columnThisMonthAmount = base.Columns["ThisMonthAmount"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnYYYYMM = new global::System.Data.DataColumn("YYYYMM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYYYYMM);
                this.columnSoukoCD = new global::System.Data.DataColumn("SoukoCD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSoukoCD);
                this.columnSoukoName = new global::System.Data.DataColumn("SoukoName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSoukoName);
                this.columnSKUCD = new global::System.Data.DataColumn("SKUCD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSKUCD);
                this.columnJanCD = new global::System.Data.DataColumn("JanCD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJanCD);
                this.columnSKUName = new global::System.Data.DataColumn("SKUName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSKUName);
                this.columnLastMonthQuantity = new global::System.Data.DataColumn("LastMonthQuantity", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLastMonthQuantity);
                this.columnLastMonthAmount = new global::System.Data.DataColumn("LastMonthAmount", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLastMonthAmount);
                this.columnThisMonthArrivalQ = new global::System.Data.DataColumn("ThisMonthArrivalQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthArrivalQ);
                this.columnThisMonthPurchaseQ = new global::System.Data.DataColumn("ThisMonthPurchaseQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthPurchaseQ);
                this.columnThisMonthPurchaseA = new global::System.Data.DataColumn("ThisMonthPurchaseA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthPurchaseA);
                this.columnThisMonthSalesQ = new global::System.Data.DataColumn("ThisMonthSalesQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthSalesQ);
                this.columnThisMonthSalesA = new global::System.Data.DataColumn("ThisMonthSalesA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthSalesA);
                this.columnThisMonthMoveInQ = new global::System.Data.DataColumn("ThisMonthMoveInQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthMoveInQ);
                this.columnThisMonthMoveOutQ = new global::System.Data.DataColumn("ThisMonthMoveOutQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthMoveOutQ);
                this.columnThisMonthAnyQ = new global::System.Data.DataColumn("ThisMonthAnyQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthAnyQ);
                this.columnThisMonthAnyA = new global::System.Data.DataColumn("ThisMonthAnyA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthAnyA);
                this.columnTotalPurchaseGaku = new global::System.Data.DataColumn("TotalPurchaseGaku", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTotalPurchaseGaku);
                this.columnThisMonthQuantity = new global::System.Data.DataColumn("ThisMonthQuantity", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthQuantity);
                this.columnLastMonthCost = new global::System.Data.DataColumn("LastMonthCost", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLastMonthCost);
                this.columnThisMonthCost = new global::System.Data.DataColumn("ThisMonthCost", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthCost);
                this.columnAveragePurchaseGaku = new global::System.Data.DataColumn("AveragePurchaseGaku", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAveragePurchaseGaku);
                this.columnExpense = new global::System.Data.DataColumn("Expense", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExpense);
                this.columnColorSize = new global::System.Data.DataColumn("ColorSize", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnColorSize);
                this.columnThisMonthShippingQ = new global::System.Data.DataColumn("ThisMonthShippingQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthShippingQ);
                this.columnThisMonthAmount = new global::System.Data.DataColumn("ThisMonthAmount", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThisMonthAmount);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DT_D_PurchaseRow NewDT_D_PurchaseRow() {
                return ((DT_D_PurchaseRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new DT_D_PurchaseRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(DT_D_PurchaseRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DT_D_PurchaseRowChanged != null)) {
                    this.DT_D_PurchaseRowChanged(this, new DT_D_PurchaseRowChangeEvent(((DT_D_PurchaseRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DT_D_PurchaseRowChanging != null)) {
                    this.DT_D_PurchaseRowChanging(this, new DT_D_PurchaseRowChangeEvent(((DT_D_PurchaseRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DT_D_PurchaseRowDeleted != null)) {
                    this.DT_D_PurchaseRowDeleted(this, new DT_D_PurchaseRowChangeEvent(((DT_D_PurchaseRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DT_D_PurchaseRowDeleting != null)) {
                    this.DT_D_PurchaseRowDeleting(this, new DT_D_PurchaseRowChangeEvent(((DT_D_PurchaseRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveDT_D_PurchaseRow(DT_D_PurchaseRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ZaikoKanriHyou_DS ds = new ZaikoKanriHyou_DS();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "DT_D_PurchaseDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class DT_D_PurchaseRow : global::System.Data.DataRow {
            
            private DT_D_PurchaseDataTable tableDT_D_Purchase;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal DT_D_PurchaseRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDT_D_Purchase = ((DT_D_PurchaseDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string YYYYMM {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.YYYYMMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'YYYYMM\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.YYYYMMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SoukoCD {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.SoukoCDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SoukoCD\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.SoukoCDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SoukoName {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.SoukoNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SoukoName\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.SoukoNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SKUCD {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.SKUCDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SKUCD\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.SKUCDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string JanCD {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.JanCDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JanCD\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.JanCDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SKUName {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.SKUNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SKUName\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.SKUNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string LastMonthQuantity {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.LastMonthQuantityColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LastMonthQuantity\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.LastMonthQuantityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string LastMonthAmount {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.LastMonthAmountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LastMonthAmount\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.LastMonthAmountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthArrivalQ {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthArrivalQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthArrivalQ\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthArrivalQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthPurchaseQ {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthPurchaseQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthPurchaseQ\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthPurchaseQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthPurchaseA {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthPurchaseAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthPurchaseA\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthPurchaseAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthSalesQ {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthSalesQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthSalesQ\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthSalesQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthSalesA {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthSalesAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthSalesA\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthSalesAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthMoveInQ {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthMoveInQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthMoveInQ\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthMoveInQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthMoveOutQ {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthMoveOutQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthMoveOutQ\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthMoveOutQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthAnyQ {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthAnyQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthAnyQ\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthAnyQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthAnyA {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthAnyAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthAnyA\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthAnyAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string TotalPurchaseGaku {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.TotalPurchaseGakuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TotalPurchaseGaku\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.TotalPurchaseGakuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthQuantity {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthQuantityColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthQuantity\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthQuantityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string LastMonthCost {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.LastMonthCostColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LastMonthCost\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.LastMonthCostColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthCost {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthCostColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthCost\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthCostColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string AveragePurchaseGaku {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.AveragePurchaseGakuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AveragePurchaseGaku\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.AveragePurchaseGakuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Expense {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ExpenseColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Expense\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ExpenseColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ColorSize {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ColorSizeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ColorSize\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ColorSizeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthShippingQ {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthShippingQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthShippingQ\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthShippingQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ThisMonthAmount {
                get {
                    try {
                        return ((string)(this[this.tableDT_D_Purchase.ThisMonthAmountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThisMonthAmount\' in table \'DT_D_Purchase\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDT_D_Purchase.ThisMonthAmountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsYYYYMMNull() {
                return this.IsNull(this.tableDT_D_Purchase.YYYYMMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetYYYYMMNull() {
                this[this.tableDT_D_Purchase.YYYYMMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSoukoCDNull() {
                return this.IsNull(this.tableDT_D_Purchase.SoukoCDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSoukoCDNull() {
                this[this.tableDT_D_Purchase.SoukoCDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSoukoNameNull() {
                return this.IsNull(this.tableDT_D_Purchase.SoukoNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSoukoNameNull() {
                this[this.tableDT_D_Purchase.SoukoNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSKUCDNull() {
                return this.IsNull(this.tableDT_D_Purchase.SKUCDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSKUCDNull() {
                this[this.tableDT_D_Purchase.SKUCDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsJanCDNull() {
                return this.IsNull(this.tableDT_D_Purchase.JanCDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetJanCDNull() {
                this[this.tableDT_D_Purchase.JanCDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSKUNameNull() {
                return this.IsNull(this.tableDT_D_Purchase.SKUNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSKUNameNull() {
                this[this.tableDT_D_Purchase.SKUNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsLastMonthQuantityNull() {
                return this.IsNull(this.tableDT_D_Purchase.LastMonthQuantityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetLastMonthQuantityNull() {
                this[this.tableDT_D_Purchase.LastMonthQuantityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsLastMonthAmountNull() {
                return this.IsNull(this.tableDT_D_Purchase.LastMonthAmountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetLastMonthAmountNull() {
                this[this.tableDT_D_Purchase.LastMonthAmountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthArrivalQNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthArrivalQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthArrivalQNull() {
                this[this.tableDT_D_Purchase.ThisMonthArrivalQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthPurchaseQNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthPurchaseQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthPurchaseQNull() {
                this[this.tableDT_D_Purchase.ThisMonthPurchaseQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthPurchaseANull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthPurchaseAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthPurchaseANull() {
                this[this.tableDT_D_Purchase.ThisMonthPurchaseAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthSalesQNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthSalesQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthSalesQNull() {
                this[this.tableDT_D_Purchase.ThisMonthSalesQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthSalesANull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthSalesAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthSalesANull() {
                this[this.tableDT_D_Purchase.ThisMonthSalesAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthMoveInQNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthMoveInQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthMoveInQNull() {
                this[this.tableDT_D_Purchase.ThisMonthMoveInQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthMoveOutQNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthMoveOutQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthMoveOutQNull() {
                this[this.tableDT_D_Purchase.ThisMonthMoveOutQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthAnyQNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthAnyQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthAnyQNull() {
                this[this.tableDT_D_Purchase.ThisMonthAnyQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthAnyANull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthAnyAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthAnyANull() {
                this[this.tableDT_D_Purchase.ThisMonthAnyAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsTotalPurchaseGakuNull() {
                return this.IsNull(this.tableDT_D_Purchase.TotalPurchaseGakuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetTotalPurchaseGakuNull() {
                this[this.tableDT_D_Purchase.TotalPurchaseGakuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthQuantityNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthQuantityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthQuantityNull() {
                this[this.tableDT_D_Purchase.ThisMonthQuantityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsLastMonthCostNull() {
                return this.IsNull(this.tableDT_D_Purchase.LastMonthCostColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetLastMonthCostNull() {
                this[this.tableDT_D_Purchase.LastMonthCostColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthCostNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthCostColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthCostNull() {
                this[this.tableDT_D_Purchase.ThisMonthCostColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAveragePurchaseGakuNull() {
                return this.IsNull(this.tableDT_D_Purchase.AveragePurchaseGakuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAveragePurchaseGakuNull() {
                this[this.tableDT_D_Purchase.AveragePurchaseGakuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsExpenseNull() {
                return this.IsNull(this.tableDT_D_Purchase.ExpenseColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetExpenseNull() {
                this[this.tableDT_D_Purchase.ExpenseColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsColorSizeNull() {
                return this.IsNull(this.tableDT_D_Purchase.ColorSizeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetColorSizeNull() {
                this[this.tableDT_D_Purchase.ColorSizeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthShippingQNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthShippingQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthShippingQNull() {
                this[this.tableDT_D_Purchase.ThisMonthShippingQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsThisMonthAmountNull() {
                return this.IsNull(this.tableDT_D_Purchase.ThisMonthAmountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetThisMonthAmountNull() {
                this[this.tableDT_D_Purchase.ThisMonthAmountColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class DT_D_PurchaseRowChangeEvent : global::System.EventArgs {
            
            private DT_D_PurchaseRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DT_D_PurchaseRowChangeEvent(DT_D_PurchaseRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DT_D_PurchaseRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591